INSERT INTO drinks
VALUES (1,'COCA-COLA ZERO','2 LTS',10,'WITHOUT_SUGAR'),(2,'COCA-COLA','2 LTS',10,'WITH_SUGAR'),(3,'SUCO DE LARANJA','1 LT',13,'WITH_SUGAR'),(4,'ÁGUA MINERAL','500 ML',3,'WITHOUT_SUGAR');

INSERT INTO hamburgers
VALUES (1,'CHEESE SALADA','CONTÉM CARNE, QUEIJO, ALFACE, TOMATE, CEBOLA!',35),(2,'X TUDO','BAGUETE, FRANGO, BACON, ETC',40),(3,'BURGER BURGER','LANCHE SIMPLES',40);

INSERT INTO ingredients
VALUES (1,'QUEIJO','',0.5,'ADDITIONAL'),(2,'PÃO','',0.3,'NOT_ADDITIONAL'),(3,'CARNE','',5,'ADDITIONAL'),(4,'ALFACE','',1,'ADDITIONAL'),(5,'TOMATE','',1,'ADDITIONAL'),(6,'CEBOLA','',1,'ADDITIONAL'),(7,'BACON','',2,'ADDITIONAL'),(8,'BATATA','',2,'ADDITIONAL'),(9,'FRANGO','',4,'ADDITIONAL'),(10,'MOLHO','',1,'NOT_ADDITIONAL');

INSERT INTO users
VALUES (2,'teste@teste.com','$2a$10$aWjFYFQzJl9rAcba.SWYDuZhviN9BeOjBvAiyzR4LtLoxdmPih2Wu');

